const RESOURCE = 'RESERVAS_';

export const SET_RESERVAS = `${RESOURCE}SET`;
export const CLEAR_RESERVAS = `${RESOURCE}CLEAR`;
export const ADD_RESERVA = `${RESOURCE}ADD`;
export const REMOVE_RESERVA = `${RESOURCE}REMOVE`;
export const MODIFY_RESERVA = `${RESOURCE}MODIFY`;
